package com.ict.twitter.plantform;

/**
 *
 * @author shanjixi
 */
public class ajaxcrawlmonitor extends javax.swing.JFrame {

    /**
     * Creates new form MainMonitor
     */
    public ajaxcrawlmonitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
    	setPreferredSize(new java.awt.Dimension(400, 300));
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelBasic = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldKeyUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTaskCount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNormalUsersCount = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelBasic.setLayout(null);

        jLabel2.setText("KeyUser数目");
        jPanelBasic.add(jLabel2);
        jLabel2.setBounds(10, 20, 90, 20);

        jTextFieldKeyUser.setText("KeyUsersCount");
        jTextFieldKeyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKeyUserActionPerformed(evt);
            }
        });
        jPanelBasic.add(jTextFieldKeyUser);
        jTextFieldKeyUser.setBounds(110, 20, 120, 21);

        jLabel3.setText("总线任务数目");
        jPanelBasic.add(jLabel3);
        jLabel3.setBounds(10, 50, 100, 15);

        jTextFieldTaskCount.setText("jTextField1");
        jPanelBasic.add(jTextFieldTaskCount);
        jTextFieldTaskCount.setBounds(110, 50, 120, 21);

        jLabel4.setText("NormalUser数目");
        jPanelBasic.add(jLabel4);
        jLabel4.setBounds(10, 80, 84, 15);

        jTextFieldNormalUsersCount.setText("NormalUsersCount");
        jTextFieldNormalUsersCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNormalUsersCountActionPerformed(evt);
            }
        });
        jPanelBasic.add(jTextFieldNormalUsersCount);
        jTextFieldNormalUsersCount.setBounds(110, 80, 120, 21);
        jPanelBasic.add(jSeparator1);
        jSeparator1.setBounds(0, 150, 400, 10);

        jLabel5.setText("当前采集状态");
        jPanelBasic.add(jLabel5);
        jLabel5.setBounds(10, 110, 90, 15);

        jTextField1.setText("采集状态");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanelBasic.add(jTextField1);
        jTextField1.setBounds(110, 110, 120, 21);

        jLabel6.setText("每分钟执行任务数");
        jPanelBasic.add(jLabel6);
        jLabel6.setBounds(10, 160, 100, 20);

        jTextField2.setText("任务数");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanelBasic.add(jTextField2);
        jTextField2.setBounds(110, 160, 120, 21);

        jLabel7.setText("更新间隔S");
        jPanelBasic.add(jLabel7);
        jLabel7.setBounds(250, 20, 60, 20);

        jTextField3.setText("60");
        jPanelBasic.add(jTextField3);
        jTextField3.setBounds(310, 20, 30, 21);

        jButton1.setText("ok");
        jPanelBasic.add(jButton1);
        jButton1.setBounds(350, 20, 45, 23);

        jTabbedPane1.addTab("基本信息", jPanelBasic);

        jPanel2.setLayout(null);

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 42, 15);

        jTabbedPane1.addTab("详细信息", jPanel2);

        getContentPane().add(jTabbedPane1, "card2");

        pack();
    }// </editor-fold>

    private void jTextFieldKeyUserActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextFieldNormalUsersCountActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajaxcrawlmonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajaxcrawlmonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajaxcrawlmonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajaxcrawlmonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajaxcrawlmonitor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBasic;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldKeyUser;
    private javax.swing.JTextField jTextFieldNormalUsersCount;
    private javax.swing.JTextField jTextFieldTaskCount;
    // End of variables declaration
}
